# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanjia',
            name='cityname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fanjia',
            name='fanjia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fanjia',
            name='sara',
            field=models.CharField(max_length=50),
        ),
    ]
