# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20180313_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanjia',
            name='bili',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
