# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-14 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20180314_0939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fanjia',
            new_name='Fangjia',
        ),
    ]
